import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./styles/globals.css";
import HeaderLi from "@/utils/HeaderLi";
import Sidebar from "@/layout/Sidebar";

const mavenPro = Maven_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Çağatay Çalışkan",
  description: "Generated by Çağatay Çalışkan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22><text y=%2214%22 font-size=%2214%22>💻</text></svg>"
        />
      </head>
      <body className={`${mavenPro.className} min-h-screen flex`}>
        <Sidebar />
        <div className="flex-grow flex flex-col">
          <header className="flex items-center justify-end p-8">
            <nav>
              <ul className="flex space-x-10 mr-2 sm:mr-6">
                <HeaderLi href="/">HOME</HeaderLi>
                <HeaderLi href="/about">ABOUT ME</HeaderLi>
                <HeaderLi href="/contact">CONTACT</HeaderLi>
              </ul>
            </nav>
          </header>

          <main className="flex-grow flex flex-col items-center justify-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
