import { Inter } from "next/font/google";
import "./styles/globals.css";
import Link from 'next/link';
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Çağatay Çalışkan",
  description: "Generated by Çağatay Çalışkan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22><text y=%2214%22 font-size=%2214%22>💻</text></svg>"
        />
      </head>
      <body className={inter.className}>
        {/* <AppLayout> */}
        <main className="flex min-h-screen flex-col items-center justify-between  ">

          <Header />

          {children}
          {/* </AppLayout> */}

          <Footer />

        </main>
      </body>
    </html>
  );
}
