import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./styles/globals.css";
import Sidebar from "@/layout/Sidebar";
import Header from "@/layout/Header";

const mavenPro = Maven_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Çağatay Çalışkan",
  description: "Generated by Çağatay Çalışkan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22><text y=%2214%22 font-size=%2214%22>💻</text></svg>"
        />
      </head>
      <body className={`${mavenPro.className} min-h-screen flex flex-col`}>
        <Header />
        <div className="flex flex-1 w-full">
          <Sidebar />
          <main className="flex-grow p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
