import { Inter } from "next/font/google";
import "./globals.css";
import AppLayout from "@/layout/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Çağatay Çalışkan",
  description: "Generated by Çağatay Çalışkan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22><text y=%2214%22 font-size=%2214%22>💻</text></svg>"
        />
      </head>
      <body className={inter.className}>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
