import { Inter } from "next/font/google";
import "./styles/globals.css";
import AppLayout from "@/layout/AppLayout";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Çağatay Çalışkan",
  description: "Generated by Çağatay Çalışkan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22><text y=%2214%22 font-size=%2214%22>💻</text></svg>"
        />
      </head>
      <body className={inter.className}>
        {/* <AppLayout> */}
        <main className="flex min-h-screen flex-col items-center justify-between p-24 bg-black">

          <header className='flex items-center justify-between bg-black p-10'>
            <nav>
              <ul className='flex space-x-4'>
                <li>
                  <Link href="/" passHref legacyBehavior>
                    <a className='text-blue-500 hover:text-blue-700'>Home</a>
                  </Link>
                </li>
                <li>
                  <Link href="/about" passHref legacyBehavior>
                    <a className='text-blue-500 hover:text-blue-700'>About Me</a>
                  </Link>
                </li>
                <li>
                  <Link href="/contact" passHref legacyBehavior>
                    <a className='text-blue-500 hover:text-blue-700'>Contact</a>
                  </Link>
                </li>
              </ul>
            </nav>
          </header>

          {children}
          {/* </AppLayout> */}


          <footer>
            <div className='items-center justify-between bg-yellow-200'>Footer</div>

          </footer>
        </main>
      </body>
    </html>
  );
}
